---
# handlers file for wordpress

    - name: restart_nginx
      service:
        name: nginx
        state: restarted
      become: true
    - name: restart_php-fpm
      service:
        name: php-fpm
        state: restarted
      become: true

...
