---
    - name: associate elastic ip
      ec2_eip:
        region: "{{ region }}"
        in_vpc: true
        state: present
        device_id: "{{ ec2_retrieved.instances[0].id }}"
        reuse_existing_ip_allowed: yes
      register: eip_var
      tags:
        - provision
      notify:
        - refresh aws dynamic inventory

    - meta: flush_handlers
      tags:
        - provision

    - meta: refresh_inventory
      tags:
        - provision

    - name: output elastic ip data
      debug:
        msg: "{{ eip_var }}"
      when: eip_var is defined
      tags:
        - debug

    - name: output elastic ip id
      debug:
        msg: "{{ eip_var.allocation_id }}"
      when: eip_var.allocation_id is defined
      tags:
        - debug

    - name: output elastic ip public address
      debug:
        msg: "{{ eip_var.public_ip }}"
      when: eip_var.allocation_id is defined
      tags:
        - debug



...

