---
- hosts: wp
  become: yes
  tasks:
  
    - name: allow https
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: yes
      become: true

    - name: allow http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
      become: true

    - name: Install EPEL-Release Yum Repository
      yum_repository:
        name: epel
        description: EPEL Yum Repository
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: Install ngnix repo rpm
      yum:
        name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
      become: true


    - name: Install vim
      yum:
        name: vim
        state: present

    - name: Install @base
      yum:
        name: "@base"
        state: present


    - name: Install git
      yum:
        name: git
        state: present


    - name: Install tcpdump
      yum:
        name: vim
        state: present

    - name: Install nmap-ncat
      yum:
        name: nmap-ncat
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Install mariadb
      yum:
        name: mariadb
        state: present

    - name: Install mariadb-server
      yum:
        name: mariadb-server
        state: present
      become: true
    - name: Install tcpdump
      yum:
        name: vim
        state: present

    - name: Install php
      yum:
        name: php
        state: present
      become: true

    - name: Install php-fpm
      yum:
        name: php-fpm
        state: present
      become: true

    - name: Install php-mysql
      yum:
        name: php-mysql
        state: present

    - name: Download and unarchive the latest wordpress files
      unarchive:
        src: http://wordpress.org/latest.tar.gz
        dest: /home/admin/
        remote_src: yes

    - name: Copy nginx.conf
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf 

    - name: Copy php.ini
      copy:
        src: files/php.ini
        dest: /etc/php.ini

    - name: Copy www.conf
      copy:
        src: files/www.conf
        dest: /etc/php-fpm.d/www.con

    - name: Copy wp-config.php
      copy:
        src: files/wp-config.php
        dest: wordpress/wp-config.php

    - copy: content="<?php phpinfo(); ?>" dest="/usr/share/nginx/html/info.php"
      become: true

    - name: rsync
      command: >
        rsync -avP /home/admin/wordpress /usr/share/nginx/html/

    - name: Change Ownership for nginx files
      file:
        path: /usr/share/nginx/html
        owner: admin
        group: nginx
      become: true

    - name: configure mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
      become: true

    - name: configure nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: true

    - name: configure php-fpm service
      service:
        name: php-fpm
        state: started
        enabled: yes
      become: true

    - script: files/wp_mariadb_config.sh

    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
      become: true

...

