---
# handlers file for mariadb


    - name: disable mariadb root account remotely
      command: 'mysql --user=root -NBe "{{ item }}"'
      with_items:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: false

    - name: set root password
      mysql_user:
        login_user: root
        name: root
        password: "nasp19"

    - name: remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "nasp19"


    - name: delete testdb
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "nasp19"

    - name: restart mariadb service
      service:
        name: mariadb
        state: restarted
      become: true



