---
    - name: extract wordpress
      unarchive:
        src: http://wordpress.org/latest.tar.gz
        dest: /home/centos/
        remote_src: true

    - name: move configuration file
      copy:
        src: ../files/wp-config.php
        dest: wordpress/wp-config.php

    - name: copy files to nginx
      command: rsync -avP wordpress/ /usr/share/nginx/html/
      become: true
      notify:
        - restart_nginx
        - restart_php-fpm
   
    - name: create wordpress db
      mysql_db:
        login_user: "{{ mariadb_priv_user }}"
        login_password: "nasp19"
        name: "wordpress"
        state: present

    - name: create wordpress db user 
      mysql_user: 
        login_user: "{{ mariadb_priv_user }}"
        login_password: "{{ mariadb_priv_user_passwd }}"
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_user_passwd }}"
        priv: "{{ wordpress_db }}.*:ALL"
        state: present


    - name: set wordpress permissions
      file: 
        path: /usr/share/nginx/html/
        owner: centos
        group: nginx
        recurse: yes
      become: true
      notify:
        - restart php-fpm service
        - restart nginx service
        - restart mariadb service 


...
