---
# tasks file for nginx


    - name: allow https
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: yes
      become: true

    - name: allow http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
      become: true

    - name: install nginx
      yum:
        name: nginx
        state: present
      become: true

    - name: enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
      become: true

    - name: copy nginx.conf
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: true
      notify:
        - restart_nginx
    - name: change ownership
      file:
        path: /usr/share/nginx/html/
        owner: admin
        group: nginx
      become: true

    - meta: flush_handlers

