---
# tasks file for php


    - name: php install
      yum:
        name: php
        state: present
      become: true

    - name: php-mysql install
      yum:
        name: php-mysql
        state: present
      become: true

    - name: php-fpm install
      yum:
        name: php-fpm
        state: present
      become: true
  
    - name: Start & enable php-fpm
      service:
        name: php-fpm
        state: started
        enabled: yes
      become: true

    - name: copy php.ini file
      copy:
        src: ../files/php.ini
        dest: /etc/php.ini
      become: true
      notify:
        - restart_php-fpm

    - name: Create php.info file for testing
      file:
        path: /usr/share/nginx/html/info.php
        state: touch
      become: true

    - copy: content="<?php phpinfo(); ?>" dest="/usr/share/nginx/html/info.php"
      become: true

    - name: php config file copy
      copy:
        src: ../files/www.conf
        dest: /etc/php-fpm.d/www.conf
      become: true
      notify:
        - restart_php-fpm


    - meta: flush_handlers
